### ISSUE TITLE
motd ASCII only?

### ISSUE THREAD

**Issue by Veraellyunjie** [adsr/rw.rs#214]
`(Psst, write up to 24 bytes in a file called ~/motd)` - greeting upon ssh-ing

It doesn't say ASCII, I tried:

`٩(^‿^)۶`, taken from https://asciimoji.com/

`٩(^‿^)۶` - `cat motd`, seems to work

`(^^)` - greeting upon ssh-ing - no, it doesn't work

**Comment by adsr** [comment]
There's an aggressive filter here:

https://github.com/adsr/rw.rs/blob/4b1e80b6af4b09ba988e17e8940fec73e2d982b5/bin/gen_motd.sh#L21

The intent was to limit the motd message to 24 bytes of printable ASCII. I'm fine accepting 24 columns of UTF-8 instead.

Maybe there's a way to invoke `tr` so that it reads UTF-8. If not we can replace it with a script. Feel free to submit a PR. Otherwise I'll get to it soon.
