### ISSUE TITLE
`ssh` works while `scp` fails, `authorized_keys` gets reverted

### ISSUE THREAD

**Issue by Veraellyunjie** [adsr/rw.rs#215]
2-fold issue.

---

My 1st ssh key is with passphrase.
I added 2nd passphraseless public key to `~/.ssh/authorized_keys` on rw.rs
and `~/.ssh/config` on my local machine:
```
Host rw.rs
        User         v11e
        IdentityFile ~/.ssh/v11e_nopassphrase@rw.rs
```

`ssh rw.rs` just logs me in.
`echo TEST > /tmp/test; scp /tmp/test rw.rs:` - this doesn't work saying:
```
subsystem request failed on channel 0
scp: Connection close
```

---

And after awhile, neither `ssh` nor `scp` work and `~/.ssh/authorized_keys` on rw.rs no longer has 2nd public key, only 1st one.

---

1. how do I make `scp` work?
2. what happens to `~/.ssh/authorized_keys` on rw.rs?

**Comment by adsr** [comment]
> how do I make scp work?

scp is disabled because I don't know if it's possible to make it run under a systemd slice. The [slice](https://github.com/adsr/rw.rs/blob/4b1e80b6af4b09ba988e17e8940fec73e2d982b5/etc/user-restricted.slice.conf) is in place to prevent abuse[^1]. As an alternative you can upload files to github and then wget/curl. Sorry I know that is annoying.

> what happens to ~/.ssh/authorized_keys on rw.rs?

`authorized_keys` is kept in sync with whatever is in `users/`. You can add the 2nd key to `users/v11e/authorized_keys` and submit a PR for that.

[^1]: Ideally I want users to do whatever they want, but unfortunately several times people have used rw.rs for scams or other malicious activity, and as a result I'm on the last strike with the hosting provider. I just asked in the tildeverse IRC channel if anyone has ideas on how to work around this other than locking down the service.

**Comment by Veraellyunjie** [comment]
I see.

> scp is disabled

`sshfs` is disabled either?
Or is it me issuing wrong command?

---

Thank you for continuing the service, even if in restricted mode

**Comment by adsr** [comment]
@Veraellyunjie can you try something like this?

```
$ mkdir ~/rwrs_mount
$ sshfs -o sftp_server=/usr/lib/sftp-server adsr@rw.rs:/home/adsr ~/rwrs_mount
```

**Comment by Veraellyunjie** [comment]
Man, this mounts! :clap:

I am on OpenBSD, where sshfs needs more flags
https://dataswamp.org/~solene/2022-07-23-openbsd-sshfs.html#_The_solution

My full command:
```
doas /usr/local/bin/sshfs -o idmap=user,allow_other,uid=1000,gid=1000,IdentityFile=/home/v11e/.ssh/v11e@rw.rs,sftp_server=/usr/lib/sftp-server v11e@rw.rs: /mnt/rw.rs
```
